### ISSUE TITLE
Reference a randomly named bucket?

### ISSUE THREAD

**Issue by cnuss** [coyoteecd/serverless-s3-cleaner#4]
I have a S3 bucket in serverless.yaml resources:

```
resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'AES256'
```

Note: I've left off the `BucketName` property, so I get a random-ish bucket name.

In `serverless.yaml` its possible to use the `Ref` syntax for dynamic injection of the bucket name, for example with `environment`:

```
provider:
  name: aws
  # ...SNIP...
  environment:
    BUCKET_NAME: { Ref: Bucket }
```

Is there a method to "inject" the randomized bucket name from CloudFormation State?  Ideally I'd like to do something like:

```
plugins:
  - serverless-s3-cleaner

custom:
  serverless-s3-cleaner:
    prompt: false
    buckets:
      - { Ref: Bucket } # or something similar to get the bucket name
```
